var isCategoryValid = false;
var $selectedCategoryText = "";
var categories; 
var consumerLoggedIn = false;
var $isConsumerLocationValid = false;
var $isJobLocationValid = false;
var isJobDescriptionValid = false;
var isLongDescriptionValid = false;
var isBudgetValid = false;
var isUserTypeValid = false;
