var isCategoryValid = false;
var $selectedCategoryText = "";
var categories; 
var consumerLoggedIn = false;
var $isConsumerLocationValid = false;
var $isJobLocationValid = false;
var isJobDescriptionValid = false;
var isLongDescriptionValid = false;
var isBudgetValid = false;
var isUserTypeValid = false;
var isFirstNameValid = false;
var isLastNameValid = false;
var isMobileNumberValid = false;
var isEmailAddressValid = false;
var isPasswordValid = false;